apiVersion: jobset.x-k8s.io/v1alpha1
kind: JobSet
metadata:
  name: jupyter
spec:
  suspend: false
  replicatedJobs:
  - name: rj
    network:
      enableDNSHostnames: true
    template:
      spec:
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: jupyterlab
              imagePullPolicy: IfNotPresent
              image: jupyter/tensorflow-notebook:latest
              securityContext:
                runAsUser: 1000
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
                requests:
                  memory: 1Gi
                  cpu: 1
              ports:
                - containerPort: 8888
                  name: jupyterlab
              env:
              - name: JUPYTER_TOKEN
                value: testing
